# Generated by Django 4.2.13 on 2024-07-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='field_2',
            field=models.CharField(default='Hello world'),
        ),
        migrations.AddField(
            model_name='comment',
            name='field_3',
            field=models.CharField(null=True),
        ),
    ]
