# Generated by Django 4.2.13 on 2024-07-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_field_2_comment_field_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='field_2',
            field=models.IntegerField(default=42),
        ),
    ]
