# Generated by Django 4.2.13 on 2024-07-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_field_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='field_3',
        ),
    ]
